### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by tituspijean**
👀 

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
FYI I'm having issues with PHP-FPM7.4 in Bullseye. (`Warning: /usr/share/yunohost/helpers.d/php: line 237: php-fpm7.4: command not found`)

**Comment by ericgaspar** [comment]
Those PHP issues...

**Comment by tituspijean** [comment]
Found the issue, it was due to an old `lychee_ynh` which had not removed its php config. Onto adding PHP deps in the script. ;)

**Comment by ericgaspar** [comment]
oh yes, I also had this problem... Did you identify the problem with Lychee not removing the PHP configuration?

**Pull request merged**
